### ISSUE TITLE
Fix exports

### ISSUE THREAD

**Issue by matthieubosquet** [solid-contrib/access-control-policy#1]
The exports aren’t configured properly meaning imports have to include the dist folder in their path.

See: https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1433/files#r976806977

**Comment by joachimvh** [comment]
The reason is the package.json I think: https://github.com/solid-contrib/access-control-policy/blob/789f6eb1095c6d8f77e1fcd66eca6a21d017ca11/package.json#L20-L21

There is no index file in this project, it's called `mod.ts`.

**Comment by matthieubosquet** [comment]
cc @joachimvh: fixed in 0.1.3.

**Comment by joachimvh** [comment]
Thanks, fixed this in https://github.com/CommunitySolidServer/CommunitySolidServer/commit/9f04e28dc606e3c51e9342f35dff17bae648409c
